Update check-pull-request.yml

diff --git a/.github/workflows/check-pull-request.yml b/.github/workflows/check-pull-request.yml
--- a/.github/workflows/check-pull-request.yml
+++ b/.github/workflows/check-pull-request.yml
@@ -8,12 +8,17 @@ jobs:
   # Check that only webgpu.yml is affected by the PR
   check:
     runs-on: ubuntu-latest
+    permissions:
+      pull-requests: write
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v3
 
-      - uses: actions/create-outputs@v0.0.0-fake
-        id: test
+      - id: test
+        run: |
+          echo "summary=There was a validation error" >> "$GITHUB_OUTPUT"
+          exit 1
+
+      # Report previous step outcome as a GitHub Check for the PR
       - uses: LouisBrunner/checks-action@v2.0.0
         if: always()
         with:
